### ISSUE TITLE
Update fares & connections for all routes

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/kern-theme#12]
Once @ekeaton pushes her updates to prod, we'll need to update the fares, transit connections and external connections info for each route to match what it was on the old site. Please coordinate with each other so we can begin updating as soon as the new site is live. 

Use staging as a reference for the information.
https://kernstaging.wpengine.com/

**Comment by ekeaton** [comment]
@MarkTrillium This site is now live! 

@danielleogden I'll work on switching the maps from the demo version to Kern's map next

**Comment by ekeaton** [comment]
Oh just to note when I ran g2h there were no timetables for Route 115.

**Comment by danielleogden** [comment]
Yeah I don't see 115 in timetable displays. @MarkTrillium is this something you can do quickly or should we assign support?

**Comment by danielleogden** [comment]
@MarkTrillium please bill this time to "Website Development - 2021"

**Comment by MarkTrillium** [comment]
@ekeaton @danielleogden 
Fares, and connections updated for all routes.

remaining issues: 

- route 115 needs timetables displays built in GTFSM 
- Interactive maps route links are pulling route url from the GTFS, update route urls in GTFSM & export

- I believe we had route 220 redirecting to the DAR page while suspended.

**Comment by danielleogden** [comment]
I updated the redirect with the new route url. @ekeaton we should great WP redirects for all the service pages that changed since many of them are top search engine results.

**Comment by MarkTrillium** [comment]
GTFS with updated route urls has been posted - links on the interactive map should be updated tomorrow.

Posted new timetables including route 115

**Comment by ekeaton** [comment]
I created a manual Route page in WP for Route 220 since there wasn't one from running TCP due to it being suspended. And I created re-directs in wpengine for all the previous route urls
