### ISSUE TITLE
Upgrade TCP to version 3.9.0

### ISSUE THREAD

**Issue by chancecorbeil** [Trillium-Solutions/kern-theme#13]
Upgrade TCP to version 3.9.0
Current TCP: Version 3.3.0

GTFS feed URL:
Timetable URL:

**Comment by chancecorbeil** [comment]
- [ ] Add bootstrap accordion js and css

**Comment by chancecorbeil** [comment]
@dougTrilliumTransit This website is ready to QA. The version of TCP is 3.9.1 and it passes my tests.

**Comment by dougTrilliumTransit** [comment]
@chancecorbeil This has been QA'd and is approved to push into PROD.

Thank you.

**Comment by chancecorbeil** [comment]
This update is complete. 
TCP version 3.9.1 is on the production website: https://kerntransit.org/
