### ISSUE TITLE
Duplicate routes and timetables

### ISSUE THREAD

**Issue by ekeaton** [Trillium-Solutions/kern-theme#5]
As mention in this [ticket](https://trilliumtransit.zendesk.com/agent/tickets/49411,) routes and timetables appear twice on Kern. I've come across this before and fixed it in the past by running CSV update. I did that again today and it was resolved.

Two questions - 1. Why is it happening? and 2. Is there a longer-term solution?

**Comment by thomastrillium** [comment]
quick note that long-term solution is probably "sell them a 5-10k project
to do an update of their site including the integration of new version of
transit-custom-posts"

**Comment by danielleogden** [comment]
@ekeaton is this still an issue? Sounds like we can take care of it during the upgrade if so.

**Comment by ekeaton** [comment]
Yeah we can close this
