### ISSUE TITLE
Dial-a-ride basemap not showing up

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/kern-theme#6]
Just came across this

https://kerntransit.org/dial-a-ride/

**Comment by chancecorbeil** [comment]
Oh interesting. Yep, the console has a reference to this.

**Comment by chancecorbeil** [comment]
Interesting. It looks like the way we have that setup is deprecated.

I found this message in the console: "Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"

I'm not a mapbox expert yet, but I think I can figure this out.

**Comment by chancecorbeil** [comment]
@nome Can you help out with this task or point me in the right direction? I tried a few ideas and I'm feeling stuck.

At first I attempted to fix the base map styles in the ['Static Assets' JSON](https://github.com/Trillium-Solutions/static-assets/blob/master/gtfsmap/themes/kerncounty-ca-us/kerncounty-ca-us.json):
But the Dial-a-ride maps with the style issues are not using 'Static Assets'. 

The Dial-a-ride maps are located in [archive-dar.php](https://github.com/Trillium-Solutions/kern-theme/blob/master/archive-dar.php) and [single-dar.php](https://github.com/Trillium-Solutions/kern-theme/blob/master/single-dar.php). I haven't figured out how to update the base map styles. The current set up in these files are too different from the documentation I find at mapbox to apply their instructions.

**Comment by NomeQ** [comment]
These are the older, Leaflet maps (as opposed to the newer, mapbox-gl maps). For now, the map is instantiated at `var map = L.mapbox.map('map', 'trilliumtransit.j3p18nh0', {touchZoom:false, scrollWheelZoom:false});` 

The line 'trilliumtransit.j3p18nh0' is the style ID. I would first try replacing it with a newer map style ID. The string might be `streets-v11` or `mapbox://styles/mapbox/streets-v11` 

If it doesn't work, we may want to upgrade to mapbox-gl.

**Comment by chancecorbeil** [comment]
Updating the style ID didn't work. Looks like we may want to upgrade to mapbox-gl.

**Comment by chancecorbeil** [comment]
This is fixed and ready to review in the Dev environment. Please take a look and let me know if this is ready for the Production environment.

https://kerntransitdev.wpengine.com/dial-a-ride/
https://kerntransitdev.wpengine.com/dial-a-ride/dial-mojave/

**Comment by danielleogden** [comment]
Looks great! Thank you

**Comment by chancecorbeil** [comment]
Wonderful, this update is now live on Production.
